name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone peanut 
              uses: actions/checkout@v4
    
            - name: navigate to parent folder
              run:
                cd ..

            - name: clone peanutMain
              uses: actions/checkout@v4
              with:
                repository: IMOitself/peanutMain
                path: peanutMain

            - name: check folders
              run: |
                cd peanutMain
                pwd
                echo ""
                cd ..
                pwd
                ls
              