name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone peanut 
              uses: actions/checkout@v4
    
            - name: clone peanutMain
              uses: actions/checkout@v4
              with:
                repository: IMOitself/peanutMain
                path: peanutMain

            - name: navigate to peanutMain
              run: |
                cd peanutMain
                pwd
                ls -a
                git status

              