name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone peanut 
              uses: actions/checkout@v4
              with:
                path: ./peanut
    
            - name: clone peanutMain
              uses: actions/checkout@v4
              with:
                repository: IMOitself/peanutMain
                path: ./peanutMain

            - name: check folders
              run: |
                cd
                pwd
                echo ":"
                ls

                echo ""
 
                cd work
                pwd
                echo ":"
                ls
              