name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    
            - name: navigate to 
              run:
                cd ./app/src/main
                pwd