name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone peanut 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: get necessary variables
              run: |
                # Get the number of commits in this push
                EVENTS_BEFORE=${{ github.event.before }}
                EVENTS_AFTER=${{ github.event.after }}
                COMMITS_COUNT=$(git rev-list --count --since=$EVENTS_BEFORE --until=$EVENTS_AFTER HEAD)

                echo "COMMITS_COUNT=$COMMITS_COUNT" >> $GITHUB_ENV

 
            - name: clone peanutMain
              uses: actions/checkout@v4
              with:
                repository: IMOitself/peanutMain
                path: peanutMain

            - name: override peanutMain with main folders
              run: |
                echo "□ current directory contents..."
                ls
                
                echo "□ navigate to cloned repo (peanutMain).."
                cd peanutMain
                
                echo "□ git status.."
                git status

                peanutMain=$(pwd)
                
                echo "□ delete all except the git folder.."
                ls -a
                find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +
                ls -a

                echo "□ navigate back.."
                cd ..
                ls

                echo "□ go to app/src.."
                cd app/src
                ls

                echo "□ copy the contents of 'main' folder to peanutMain.."
                cp -r main/* $peanutMain
                cd $peanutMain
                ls -a

                echo "□ git status.."
                git status

                echo "□ Number of commits in this push: $COMMITS_COUNT"
                if [$COMMITS_COUNT -le 0]; then
                  echo "□ no commits."

                else
                  echo "□ committing.."

                  cd ..
                  LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
                  echo "$LAST_COMMIT_MSG"

                  
                  cd $peanutMain
                  git add .

                  git config --global user.email "russjonn@gmail.com"
                  git config --global user.name "IMOitself (github action)"
                  git commit -m "$LAST_COMMIT_MSG"

                  echo "□ pushing.."
                  git push origin master
                fi
