name: Sync to peanutMain

on:
    push:
        branches: [master, auto]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    
            - name: navigate to main folder
              run: |
                cd ./app/src/main
                pwd
            
            - name: check outside folder
              run: |
                cd
                pwd
                ls